# Generated by Django 5.2.6 on 2025-09-12 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('price', models.PositiveIntegerField(default=100)),
                ('monthly_yield_pct', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('total_gtl', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=100)),
                ('has_starter_pack', models.BooleanField(default=False)),
                ('periodic_table', models.JSONField(default=dict)),
                ('referrals_count', models.PositiveIntegerField(default=0)),
                ('referral_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtl.miningasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtl.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtl.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_sec', models.PositiveIntegerField(default=10)),
                ('is_finished', models.BooleanField(default=False)),
                ('collected_gtl', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtl.userprofile')),
            ],
        ),
    ]
